name: user_side_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.7.1
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  email_validator: ^2.1.17
  firebase_auth: ^4.6.2
  firebase_storage: ^11.2.2
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.0.0
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get: ^4.6.5
  google_fonts: ^4.0.4
  google_sign_in: ^6.1.4
  http: ^1.1.0
  icon_decoration: ^1.0.1
  intl: ^0.18.1
  provider: ^6.0.5
  razorpay_flutter: ^1.3.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/asset/
    - lib/asset/christianwedding.jpg
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
